### ISSUE TITLE
Nonetype object has no attribute 'group'

### ISSUE THREAD

**Issue by Lod3** [ettorerizza/aat_reconcile#1]
I am trying to use the aat_reconcile service, only after starting it in openrefine the terminal shows that it is running but stops at "AttributeError: 'NoneType' object has no attribute 'group'"
```
`admin$ python reconcile.py --debug
 * Serving Flask app "reconcile" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 125-255-038
127.0.0.1 - - [23/Oct/2018 11:52:14] "GET /?callback=jQuery111109574310175641808_1540288271949&_=1540288271950 HTTP/1.1" 200 -
[2018-10-23 11:52:14,598] DEBUG in reconcile: AAT url is http://vocabsservices.getty.edu/AATService.asmx/AATGetTermMatch?term=pastel&logop=and&notes=
[2018-10-23 11:52:14,637] DEBUG in reconcile: Label is cake (food) Score is 27 URI is 300255019
[2018-10-23 11:52:14,638] DEBUG in reconcile: Label is cake pans Score is 40 URI is 300196391
[2018-10-23 11:52:14,638] DEBUG in reconcile: Label is cake plates (serving vessels) Score is 30 URI is 300043000
[2018-10-23 11:52:14,638] DEBUG in reconcile: Label is crayon manner prints Score is 15 URI is 300041519
[2018-10-23 11:52:14,638] DEBUG in reconcile: Label is oil pastels Score is 71 URI is 300230810
[2018-10-23 11:52:14,638] DEBUG in reconcile: Label is pastel (color attribute) Score is 43 URI is 300311039
[2018-10-23 11:52:14,639] DEBUG in reconcile: Label is pastel (material) Score is 57 URI is 300404632
[2018-10-23 11:52:14,639] DEBUG in reconcile: Label is pastel paper Score is 67 URI is 300183684
[2018-10-23 11:52:14,639] DEBUG in reconcile: Label is pastels (crayons) Score is 57 URI is 300122621
[2018-10-23 11:52:14,640] DEBUG in reconcile: Label is pastels (visual works) Score is 46 URI is 300076922
[2018-10-23 11:52:14,640] DEBUG in reconcile: Label is pie plates Score is 50 URI is 300196648
[2018-10-23 11:52:14,640] DEBUG in reconcile: AAT url is http://vocabsservices.getty.edu/AATService.asmx/AATGetTermMatch?term=gouache&logop=and&notes=
[2018-10-23 11:52:14,644] DEBUG in reconcile: Label is gouache (paint) Score is 70 URI is 300070114
[2018-10-23 11:52:14,645] DEBUG in reconcile: Label is gouache (technique) Score is 58 URI is 300404215
[2018-10-23 11:52:14,645] DEBUG in reconcile: Label is gouaches (paintings) Score is 56 URI is 300078928
[2018-10-23 11:52:14,645] DEBUG in reconcile: AAT url is http://vocabsservices.getty.edu/AATService.asmx/AATGetTermMatch?term=aardewerk&logop=and&notes=
[2018-10-23 11:52:14,650] DEBUG in reconcile: Label is Cistercian ware Score is 33 URI is 300264956
[2018-10-23 11:52:14,651] DEBUG in reconcile: Label is creamware Score is 44 URI is 300163214
[2018-10-23 11:52:14,651] DEBUG in reconcile: Label is crocks (vessels) Score is 26 URI is 300195273
[2018-10-23 11:52:14,651] DEBUG in reconcile: Label is delftware Score is 44 URI is 300140808
[2018-10-23 11:52:14,651] DEBUG in reconcile: Label is earthenware Score is 50 URI is 300140803
[2018-10-23 11:52:14,652] DEBUG in reconcile: Label is gray ware (visual works) Score is 45 URI is 300343408
[2018-10-23 11:52:14,652] DEBUG in reconcile: Label is greenware Score is 44 URI is 300233427
[2018-10-23 11:52:14,652] DEBUG in reconcile: Label is Longquan ware Score is 36 URI is 300404851
[2018-10-23 11:52:14,652] DEBUG in reconcile: Label is marbled ware Score is 48 URI is 300179304
[2018-10-23 11:52:14,652] DEBUG in reconcile: Label is pottery decorating techniques Score is 21 URI is 300053909
[2018-10-23 11:52:14,653] DEBUG in reconcile: Label is pottery forming techniques Score is 17 URI is 300251415
[2018-10-23 11:52:14,653] DEBUG in reconcile: Label is pottery glazing (process or technique) Score is 18 URI is 300195111
[2018-10-23 11:52:14,653] DEBUG in reconcile: Label is Pottery Neolithic Score is 23 URI is 300263188
[2018-10-23 11:52:14,653] DEBUG in reconcile: Label is Pratt ware Score is 42 URI is 300263408
[2018-10-23 11:52:14,653] DEBUG in reconcile: Label is Saint-Porchaire ware Score is 34 URI is 300264958
[2018-10-23 11:52:14,654] DEBUG in reconcile: Label is whiteware Score is 33 URI is 300233437
[2018-10-23 11:52:14,654] DEBUG in reconcile: Label is yellowware Score is 32 URI is 300233438
[2018-10-23 11:52:14,654] DEBUG in reconcile: Label is Zeuxippus ware Score is 35 URI is 300404726
[2018-10-23 11:52:14,654] DEBUG in reconcile: AAT url is http://vocabsservices.getty.edu/AATService.asmx/AATGetTermMatch?term=paard&logop=and&notes=
[2018-10-23 11:52:14,658] DEBUG in reconcile: Label is Equus caballus (species) Score is 15 URI is 300250148
[2018-10-23 11:52:14,659] DEBUG in reconcile: Label is Horse phase Score is 25 URI is 300102506
[2018-10-23 11:52:14,659] DEBUG in reconcile: Label is knights (chessmen) Score is 0 URI is 300233378
[2018-10-23 11:52:14,659] DEBUG in reconcile: Label is vaulting horses Score is 10 URI is 300211259
[2018-10-23 11:52:14,659] DEBUG in reconcile: AAT url is http://vocabsservices.getty.edu/AATService.asmx/AATGetTermMatch?term=olieverfschildering&logop=and&notes=
[2018-10-23 11:52:14,663] DEBUG in reconcile: Label is oil paintings (visual works) Score is 31 URI is 300033799
[2018-10-23 11:52:14,664] DEBUG in reconcile: AAT url is http://vocabsservices.getty.edu/AATService.asmx/AATGetTermMatch?term=foto&logop=and&notes=
[2018-10-23 11:52:14,670] DEBUG in reconcile: Label is black-and-white photographs Score is 19 URI is 300128347
[2018-10-23 11:52:14,670] DEBUG in reconcile: Label is cameras (photographic equipment) Score is 18 URI is 300022636
[2018-10-23 11:52:14,671] DEBUG in reconcile: Label is cased photographs Score is 29 URI is 300127264
[2018-10-23 11:52:14,671] DEBUG in reconcile: Label is commercial photographs Score is 23 URI is 300412092
[2018-10-23 11:52:14,671] DEBUG in reconcile: Label is copy stands Score is 27 URI is 300311735
[2018-10-23 11:52:14,671] DEBUG in reconcile: Label is documentary photographs Score is 22 URI is 300264341
[2018-10-23 11:52:14,671] DEBUG in reconcile: Label is forensic photographs Score is 33 URI is 300256470
[2018-10-23 11:52:14,672] DEBUG in reconcile: Label is frame enlargements Score is 9 URI is 300163100
[2018-10-23 11:52:14,672] DEBUG in reconcile: Label is instantaneous photographs Score is 21 URI is 300134966
[2018-10-23 11:52:14,672] DEBUG in reconcile: Label is manipulated photographs Score is 22 URI is 300127269
[2018-10-23 11:52:14,672] DEBUG in reconcile: Label is night photography Score is 29 URI is 300053449
[2018-10-23 11:52:14,672] DEBUG in reconcile: Label is photobooths Score is 40 URI is 300254678
[2018-10-23 11:52:14,673] DEBUG in reconcile: Label is photo CDs Score is 46 URI is 300263426
[2018-10-23 11:52:14,673] DEBUG in reconcile: Label is photoelasticity Score is 32 URI is 300191635
[2018-10-23 11:52:14,673] DEBUG in reconcile: Label is photoelectric photometers Score is 21 URI is 300200052
[2018-10-23 11:52:14,673] DEBUG in reconcile: Label is photoflood lamps Score is 30 URI is 300181400
[2018-10-23 11:52:14,673] DEBUG in reconcile: Label is photographs Score is 40 URI is 300046300
[2018-10-23 11:52:14,674] DEBUG in reconcile: Label is photographs by form Score is 35 URI is 300127008
[2018-10-23 11:52:14,674] DEBUG in reconcile: Label is photographs by form: color Score is 28 URI is 300127013
[2018-10-23 11:52:14,674] DEBUG in reconcile: Label is photographs by form: format Score is 27 URI is 300127015
[2018-10-23 11:52:14,674] DEBUG in reconcile: Label is photographs by function Score is 30 URI is 300127009
[2018-10-23 11:52:14,674] DEBUG in reconcile: Label is photographs by picture-taking technique Score is 14 URI is 300139768
[2018-10-23 11:52:14,675] DEBUG in reconcile: Label is photographs by processing or presentation technique Score is 11 URI is 300137294
[2018-10-23 11:52:14,675] DEBUG in reconcile: Label is photographs by subject type Score is 19 URI is 300138221
[2018-10-23 11:52:14,675] DEBUG in reconcile: Label is photographs by technique Score is 21 URI is 300127011
[2018-10-23 11:52:14,675] DEBUG in reconcile: Label is photograph viewing equipment Score is 19 URI is 300162918
[2018-10-23 11:52:14,675] DEBUG in reconcile: Label is Photo-Secession Score is 32 URI is 300108181
[2018-10-23 11:52:14,676] DEBUG in reconcile: Label is size for photograph formats Score is 26 URI is 300135449
[2018-10-23 11:52:14,676] DEBUG in reconcile: Label is staged photographs Score is 27 URI is 300184557
[2018-10-23 11:52:14,676] DEBUG in reconcile: AAT url is http://vocabsservices.getty.edu/AATService.asmx/AATGetTermMatch?term=temperaschildering&logop=and&notes=
[2018-10-23 11:52:14,681] DEBUG in reconcile: AAT url is http://vocabsservices.getty.edu/AATService.asmx/AATGetTermMatch?term=tekeningen&logop=and&notes=
[2018-10-23 11:52:14,690] DEBUG in reconcile: Label is axonometric projections (images) Score is 25 URI is 300034021
[2018-10-23 11:52:14,691] DEBUG in reconcile: Label is blotted line drawings (drawings) Score is 35 URI is 300265072
[2018-10-23 11:52:14,692] DEBUG in reconcile: Label is cabinet oblique drawings Score is 29 URI is 300033998
[2018-10-23 11:52:14,693] DEBUG in reconcile: Label is cavalier oblique drawings Score is 29 URI is 300034003
[2018-10-23 11:52:14,693] DEBUG in reconcile: Label is cutaways (images) Score is 32 URI is 300072982
192.168.1.45 - - [23/Oct/2018 11:52:14] "POST / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/packed-admin/Desktop/aat_reconcile/reconcile.py", line 133, in reconcile
    data = search(query['query'])
  File "/Users/packed-admin/Desktop/aat_reconcile/reconcile.py", line 104, in search
    id = re.search(r"\[(.+?)\]", child.text.split(',')[0]).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
`
```
Any help would be appreciated, thanks.

**Comment by ettorerizza** [comment]
Hello @Lod3, thanx for your report. This is an alpha version probably full of bugs. I have to take a day to solve them and add features (matches with TGN, ULAN ...). I will try to do this as soon as possible.

**Comment by jb221467** [comment]
Any luck with this bug? I am having the same issue

**Comment by ettorerizza** [comment]
Sorry for the delayed response, it should work correctly now.
